#!/bin/bash
#
# (C) Copyright 2012 lilydjwg <lilydjwg@gmail.com>
#
# This file is part of xmpptalk.
#
# xmpptalk is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# xmpptalk is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with xmpptalk.  If not, see <http://www.gnu.org/licenses/>.
#

prefix=${prefix:-/usr/local}

mkdir -p $prefix/var/{lib,log}/mongodb
touch $prefix/var/log/mongodb/mongodb.log

id mongo >/dev/null 2>/dev/null || useradd -d $prefix/var/lib/mongodb -r mongo

chown -R mongo $prefix/var/{lib,log}/mongodb

cd $(dirname $0)
cp ./mongodb.conf.example $prefix/etc/mongodb.conf
[[ prefix = /usr/local ]] || sed -i "s=/usr/local=$prefix=g" $prefix/etc/mongodb.conf
