#!/bin/bash
#
# (C) Copyright 2012 lilydjwg <lilydjwg@gmail.com>
#
# This file is part of xmpptalk.
#
# xmpptalk is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# xmpptalk is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with xmpptalk.  If not, see <http://www.gnu.org/licenses/>.
#

xgettext --keyword=N_:1,2 --from-code=utf-8 -p po `find -type f -name '*.py'`
cd po && msgmerge -U zh_CN.po messages.po
cd - > /dev/null
msgfmt -c -v -o locale/zh_CN/LC_MESSAGES/xmpptalk.mo po/zh_CN.po
